cp TUTOMSG_SONIC_E_HD/sprf_01_e.png TUTOMSG_TAILS_E_HD/sprf_01_e.png
cp TUTOMSG_SONIC_E_HD/sprf_02_e.png TUTOMSG_TAILS_E_HD/sprf_02_e.png
cp TUTOMSG_SONIC_E_HD/sprf_04_e.png TUTOMSG_TAILS_E_HD/sprf_04_e.png
cp TUTOMSG_TAILS_E_HD/tprf_06_e.png TUTOMSG_KNUCKLES_E_HD/tprf_06_e.png
cp TUTOMSG_AMY_E_HD/aprf_04_e.png TUTOMSG_BIG_E_HD/aprf_04_e.png
cp TUTOMSG_AMY_E_HD/aprf_04_e.png TUTOMSG_E102_E_HD/aprf_04_e.png